---
server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/sms-service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update